{% set name = "napari-crop" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-crop-{{ version }}.tar.gz
  sha256: 54949ae74ab2fe118d33309d31b8c7eb7368de65428f1008038b82232d8856bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >={{ python_min }}
    - scikit-image
    - napari-workflows

test:
  imports:
    - napari_crop
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/biapol/napari-crop
  summary: Crop regions in napari manually
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
    - zoccoler
